In [1]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn import preprocessing
from numpy.random import seed
from skimage.io import imread_collection
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from skimage.io import imread_collection
import seaborn as sns
import matplotlib.pyplot as plt
import os
os.environ['PYTHONHASHSEED'] = '0'
np.random.seed(37)
tf.random.set_seed(89)
train_new_model = True

In [2]:
def accuracy(true,result):
    score = (accuracy_score(true,result)*100)
    print("Accuracy: ",score,"%")
    # return score
    
def confusion(true,result):
    cm = confusion_matrix(true,result)
    print(cm)
    # return cm

In [3]:
images = np.array(imread_collection(r'./Train/*.jpg'))

train=np.zeros((2400, 784))
for i in range(len(images)):
    train[i]=images[i].flatten()

In [4]:
test_images = np.array(imread_collection(r'./Test/*.jpg'))
test=np.zeros((200, 784))
for i in range(len(test_images)):
    test[i]=test_images[i].flatten()

In [5]:
labels = np.loadtxt(r"./Train/Training Labels.txt", dtype=int)
labels_test = np.loadtxt(r"./Test/Test Labels.txt", dtype=int)

In [6]:
X_train = tf.convert_to_tensor(tf.constant(train, dtype=tf.float32))
Y_train = tf.keras.utils.to_categorical(labels, 10)
standard_train = preprocessing.StandardScaler().fit_transform(X_train)

In [7]:
X_test = tf.convert_to_tensor(tf.constant(test , dtype = tf.float32))
Y_test = tf.keras.utils.to_categorical(labels_test, 10)
standard_test = preprocessing.StandardScaler().fit_transform(X_test)

In [8]:
#First Requirement

model1 = tf.keras.models.Sequential()
model1.add(tf.keras.layers.Flatten())
model1.add(tf.keras.layers.Dense(units=500, activation=tf.nn.relu))
model1.add(tf.keras.layers.Dense(units=10, activation=tf.nn.sigmoid))
model1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mean_squared_error',metrics=['binary_accuracy'])
model1.fit(standard_train, Y_train, epochs=100)

Epoch 1/100
75/75 [==============================] - 0s 2ms/step - loss: 0.0468 - binary_accuracy: 0.9362
Epoch 2/100
75/75 [==============================] - 0s 2ms/step - loss: 0.0111 - binary_accuracy: 0.9885
Epoch 3/100
75/75 [==============================] - 0s 2ms/step - loss: 0.0057 - binary_accuracy: 0.9948
Epoch 4/100
75/75 [==============================] - 0s 2ms/step - loss: 0.0034 - binary_accuracy: 0.9973
Epoch 5/100
75/75 [==============================] - 0s 2ms/step - loss: 0.0022 - binary_accuracy: 0.9985
Epoch 6/100
75/75 [==============================] - 0s 2ms/step - loss: 0.0017 - binary_accuracy: 0.9988
Epoch 7/100
75/75 [==============================] - 0s 2ms/step - loss: 0.0014 - binary_accuracy: 0.9989
Epoch 8/100
75/75 [==============================] - 0s 2ms/step - loss: 0.0012 - binary_accuracy: 0.9990
Epoch 9/100
75/75 [==============================] - 0s 2ms/step - loss: 0.0011 - binary_accuracy: 0.9991
Epoch 10/100
75/75 [==========================

In [9]:
prediction = model1.predict([standard_test])
prect = []
for i in range(len(prediction)):
    prect.append(np.argmax(prediction[i]))

Consider rewriting this model with the Functional API.


In [10]:
accuracy(labels_test,prect)
confusion(labels_test,prect)

Accuracy:  91.5 %
[[18  0  0  0  0  0  1  1  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  1 17  1  0  0  0  0  1  0]
 [ 0  0  0 20  0  0  0  0  0  0]
 [ 0  0  0  0 18  0  0  0  0  2]
 [ 0  0  0  1  0 19  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 18  0  2]
 [ 0  0  0  1  0  0  0  0 19  0]
 [ 0  0  1  2  0  0  0  3  0 14]]


In [11]:
#Second Requirement

tf.keras.backend.clear_session()
model2 = tf.keras.models.Sequential()
model2.add(tf.keras.layers.Flatten())
model2.add(tf.keras.layers.Dense(units=500, activation=tf.nn.relu))
model2.add(tf.keras.layers.Dense(units=10, activation=tf.nn.sigmoid))
model2.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mean_squared_error',metrics=['binary_accuracy'])
model2.fit(standard_train, Y_train, epochs=200)

Epoch 1/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0467 - binary_accuracy: 0.9355
Epoch 2/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0110 - binary_accuracy: 0.9880
Epoch 3/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0057 - binary_accuracy: 0.9948
Epoch 4/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0034 - binary_accuracy: 0.9971
Epoch 5/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0023 - binary_accuracy: 0.9983
Epoch 6/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0017 - binary_accuracy: 0.9988
Epoch 7/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0014 - binary_accuracy: 0.9988
Epoch 8/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0012 - binary_accuracy: 0.9990
Epoch 9/200
75/75 [==============================] - 0s 2ms/step - loss: 9.8866e-04 - binary_accuracy: 0.9992
Epoch 10/200
75/75 [======================

In [12]:
prediction = model2.predict([standard_test])
prect = []
for i in range(len(prediction)):
    prect.append(np.argmax(prediction[i]))

Consider rewriting this model with the Functional API.


In [13]:
accuracy(labels_test,prect)
confusion(labels_test,prect)

Accuracy:  90.0 %
[[18  0  0  0  1  0  1  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 17  1  0  1  0  0  1  0]
 [ 1  0  0 18  0  1  0  0  0  0]
 [ 0  0  1  0 18  0  0  0  0  1]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 19  0  1  0]
 [ 0  0  0  0  0  0  0 19  0  1]
 [ 0  0  1  1  0  1  0  0 17  0]
 [ 0  0  0  1  1  1  0  3  0 14]]


Accuracies increase till a certain point when increasing epochs so when running the 200 it increased till a certain point then flatted out.

In [14]:
#Third Requirement
tf.keras.backend.clear_session()
model3 = tf.keras.models.Sequential()
model3.add(tf.keras.layers.Flatten())
model3.add(tf.keras.layers.Dense(units=500, activation=tf.nn.relu))
model3.add(tf.keras.layers.Dense(units=10, activation=tf.nn.sigmoid))
model3.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mean_squared_error',metrics=['binary_accuracy'])
model3.fit(X_train, Y_train, epochs=200)

Epoch 1/200
75/75 [==============================] - 0s 2ms/step - loss: 0.1211 - binary_accuracy: 0.8786
Epoch 2/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0996 - binary_accuracy: 0.9004
Epoch 3/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0995 - binary_accuracy: 0.9005
Epoch 4/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0992 - binary_accuracy: 0.9008
Epoch 5/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0994 - binary_accuracy: 0.9006
Epoch 6/200
75/75 [==============================] - 0s 2ms/step - loss: 0.1000 - binary_accuracy: 0.9000
Epoch 7/200
75/75 [==============================] - 0s 2ms/step - loss: 0.1000 - binary_accuracy: 0.9000
Epoch 8/200
75/75 [==============================] - 0s 2ms/step - loss: 0.1000 - binary_accuracy: 0.9000
Epoch 9/200
75/75 [==============================] - 0s 2ms/step - loss: 0.1000 - binary_accuracy: 0.9000
Epoch 10/200
75/75 [==========================

In [15]:
prediction = model3.predict([test])
prect = []
for i in range(len(prediction)):
    prect.append(np.argmax(prediction[i]))

Consider rewriting this model with the Functional API.


In [16]:
accuracy(labels_test,prect)
confusion(labels_test,prect)

Accuracy:  10.5 %
[[20  0  0  0  0  0  0  0  0  0]
 [19  1  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]]


Standardizing the data greatly increases the classification accuracy such as comparing coeffients also standardization gives all features the same influence

In [17]:
#Fourth Requirement
tf.keras.backend.clear_session()
model4 = tf.keras.models.Sequential()
model4.add(tf.keras.layers.Flatten())
model4.add(tf.keras.layers.Dense(units=500, activation=tf.nn.relu))
model4.add(tf.keras.layers.Dense(units=10, activation=tf.nn.sigmoid))
model4.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), loss='mean_squared_error',metrics=['binary_accuracy'])
model4.fit(standard_train, Y_train, epochs=200)

Epoch 1/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0628 - binary_accuracy: 0.9314
Epoch 2/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0502 - binary_accuracy: 0.9485
Epoch 3/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0488 - binary_accuracy: 0.9503
Epoch 4/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0517 - binary_accuracy: 0.9477
Epoch 5/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0479 - binary_accuracy: 0.9516
Epoch 6/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0464 - binary_accuracy: 0.9532
Epoch 7/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0521 - binary_accuracy: 0.9476
Epoch 8/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0476 - binary_accuracy: 0.9521
Epoch 9/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0466 - binary_accuracy: 0.9532
Epoch 10/200
75/75 [==========================

In [18]:
prediction = model4.predict([standard_test])
prect = []
for i in range(len(prediction)):
    prect.append(np.argmax(prediction[i]))

Consider rewriting this model with the Functional API.


In [19]:
accuracy(labels_test,prect)
confusion(labels_test,prect)

Accuracy:  63.5 %
[[17  0  0  0  0  0  2  1  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 2  0 16  0  0  0  1  0  1  0]
 [ 3  0  1 15  0  0  0  1  0  0]
 [ 3  0  0  0 14  0  3  0  0  0]
 [20  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 3  0  0  0  0  0  0 17  0  0]
 [12  0  0  0  0  0  0  0  8  0]
 [14  0  0  1  2  0  0  3  0  0]]


In [20]:
#Fifth Requirement
tf.keras.backend.clear_session()
model5 = tf.keras.models.Sequential()
model5.add(tf.keras.layers.Flatten())
model5.add(tf.keras.layers.Dense(units=500, activation=tf.nn.relu))
model5.add(tf.keras.layers.Dense(units=10, activation=tf.nn.sigmoid))
model5.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005), loss='mean_squared_error',metrics=['binary_accuracy'])
model5.fit(standard_train, Y_train, epochs=200)

Epoch 1/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0587 - binary_accuracy: 0.9239
Epoch 2/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0150 - binary_accuracy: 0.9842
Epoch 3/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0088 - binary_accuracy: 0.9925
Epoch 4/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0057 - binary_accuracy: 0.9957
Epoch 5/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0039 - binary_accuracy: 0.9976
Epoch 6/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0029 - binary_accuracy: 0.9986
Epoch 7/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0023 - binary_accuracy: 0.9989
Epoch 8/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0019 - binary_accuracy: 0.9990
Epoch 9/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0017 - binary_accuracy: 0.9991
Epoch 10/200
75/75 [==========================

In [21]:
prediction = model5.predict([standard_test])
prect = []
for i in range(len(prediction)):
    prect.append(np.argmax(prediction[i]))

Consider rewriting this model with the Functional API.


In [22]:
accuracy(labels_test,prect)
confusion(labels_test,prect)

Accuracy:  91.5 %
[[18  0  0  0  0  0  1  1  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 18  0  0  0  1  0  1  0]
 [ 0  0  1 19  0  0  0  0  0  0]
 [ 0  0  0  0 17  0  0  0  0  3]
 [ 0  0  0  0  0 20  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 18  0  2]
 [ 0  0  0  1  0  0  0  0 19  0]
 [ 0  0  0  1  1  0  0  3  1 14]]


Decreasing the learning rate increases the accuracy

In [23]:
#Sixth Requirement
tf.keras.backend.clear_session()
model6 = tf.keras.models.Sequential()
model6.add(tf.keras.layers.Flatten())
model6.add(tf.keras.layers.Dense(units=500, activation=tf.nn.relu))
model6.add(tf.keras.layers.Dense(units=100, activation=tf.nn.relu))
model6.add(tf.keras.layers.Dense(units=10, activation=tf.nn.sigmoid))
model6.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mean_squared_error',metrics=['binary_accuracy'])
model6.fit(standard_train, Y_train, epochs=200)

Epoch 1/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0480 - binary_accuracy: 0.9358
Epoch 2/200
75/75 [==============================] - 0s 3ms/step - loss: 0.0115 - binary_accuracy: 0.9860
Epoch 3/200
75/75 [==============================] - 0s 3ms/step - loss: 0.0053 - binary_accuracy: 0.9948
Epoch 4/200
75/75 [==============================] - 0s 3ms/step - loss: 0.0028 - binary_accuracy: 0.9978
Epoch 5/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0018 - binary_accuracy: 0.9986
Epoch 6/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0014 - binary_accuracy: 0.9988
Epoch 7/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0012 - binary_accuracy: 0.9989
Epoch 8/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0010 - binary_accuracy: 0.9991
Epoch 9/200
75/75 [==============================] - 0s 2ms/step - loss: 9.1076e-04 - binary_accuracy: 0.9992
Epoch 10/200
75/75 [======================

In [24]:
prediction = model6.predict([standard_test])
prect = []
for i in range(len(prediction)):
    prect.append(np.argmax(prediction[i]))

Consider rewriting this model with the Functional API.


In [25]:
accuracy(labels_test,prect)
confusion(labels_test,prect)

Accuracy:  88.5 %
[[18  0  0  0  0  0  1  1  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 18  0  0  0  1  0  1  0]
 [ 0  0  1 15  0  1  0  0  3  0]
 [ 0  0  0  0 16  0  2  0  0  2]
 [ 0  0  0  1  0 19  0  0  0  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  1  0  0 18  0  1]
 [ 0  0  0  0  0  2  0  0 17  1]
 [ 0  0  0  0  0  0  0  4  0 16]]


In [26]:
#Seventh Requirement
tf.keras.backend.clear_session()
model7 = tf.keras.models.Sequential()
model7.add(tf.keras.layers.Flatten())
model7.add(tf.keras.layers.Dense(units=500, activation=tf.nn.relu))
model7.add(tf.keras.layers.Dense(units=100, activation=tf.nn.relu))
model7.add(tf.keras.layers.Dense(units=50, activation=tf.nn.relu))
model7.add(tf.keras.layers.Dense(units=10, activation=tf.nn.sigmoid))
model7.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mean_squared_error',metrics=['binary_accuracy'])
model7.fit(standard_train, Y_train, epochs=200)

Epoch 1/200
75/75 [==============================] - 0s 3ms/step - loss: 0.0537 - binary_accuracy: 0.9332
Epoch 2/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0174 - binary_accuracy: 0.9800
Epoch 3/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0065 - binary_accuracy: 0.9932
Epoch 4/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0032 - binary_accuracy: 0.9972
Epoch 5/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0018 - binary_accuracy: 0.9985
Epoch 6/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0015 - binary_accuracy: 0.9987
Epoch 7/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0011 - binary_accuracy: 0.9990
Epoch 8/200
75/75 [==============================] - 0s 2ms/step - loss: 9.3330e-04 - binary_accuracy: 0.9991
Epoch 9/200
75/75 [==============================] - 0s 2ms/step - loss: 8.6612e-04 - binary_accuracy: 0.9992
Epoch 10/200
75/75 [==================

In [27]:
prediction = model7.predict([standard_test])
prect = []
for i in range(len(prediction)):
    prect.append(np.argmax(prediction[i]))

Consider rewriting this model with the Functional API.


In [28]:
accuracy(labels_test,prect)
confusion(labels_test,prect)

Accuracy:  89.0 %
[[18  0  0  0  0  0  1  1  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  0 18  0  0  1  0  0  1  0]
 [ 0  0  0 17  0  2  0  0  1  0]
 [ 0  1  1  0 15  0  1  0  0  2]
 [ 0  0  0  0  0 19  0  0  1  0]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 19  0  1]
 [ 0  0  0  1  0  2  0  0 17  0]
 [ 0  0  1  0  0  0  0  4  0 15]]


In [29]:
#Eighth Requirement
tf.keras.backend.clear_session()
model8 = tf.keras.models.Sequential()
model8.add(tf.keras.layers.Flatten())
model8.add(tf.keras.layers.Dense(units=500, activation=tf.nn.relu))
model8.add(tf.keras.layers.Dense(units=100, activation=tf.nn.relu))
model8.add(tf.keras.layers.Dense(units=50, activation=tf.nn.relu))
model8.add(tf.keras.layers.Dense(units=25, activation=tf.nn.relu))
model8.add(tf.keras.layers.Dense(units=10, activation=tf.nn.sigmoid))
model8.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mean_squared_error',metrics=['binary_accuracy'])
model8.fit(standard_train, Y_train, epochs=200)

Epoch 1/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0688 - binary_accuracy: 0.9145
Epoch 2/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0246 - binary_accuracy: 0.9726
Epoch 3/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0163 - binary_accuracy: 0.9834
Epoch 4/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0135 - binary_accuracy: 0.9866
Epoch 5/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0121 - binary_accuracy: 0.9883
Epoch 6/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0115 - binary_accuracy: 0.9886
Epoch 7/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0112 - binary_accuracy: 0.9890
Epoch 8/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0110 - binary_accuracy: 0.9890
Epoch 9/200
75/75 [==============================] - 0s 2ms/step - loss: 0.0109 - binary_accuracy: 0.9892
Epoch 10/200
75/75 [==========================

In [30]:
prediction = model8.predict([standard_test])
prect = []
for i in range(len(prediction)):
    prect.append(np.argmax(prediction[i]))

Consider rewriting this model with the Functional API.


In [31]:
accuracy(labels_test,prect)
confusion(labels_test,prect)

Accuracy:  81.5 %
[[19  0  0  0  1  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0 11  0  5  0  0  0  3  1  0]
 [ 0  0  0 19  0  0  0  0  1  0]
 [ 0  1  0  0 15  0  0  0  0  4]
 [ 0  0  0  0  0 18  0  0  0  2]
 [ 0  0  0  0  0  0 20  0  0  0]
 [ 0  0  0  0  0  0  0 18  0  2]
 [ 0  0  0  0  0  1  0  0 19  0]
 [ 0  0  0  0  0  0  0  5  0 15]]


In [32]:
#ninth Requirement
tf.keras.backend.clear_session()
model9 = tf.keras.models.Sequential()
model9.add(tf.keras.layers.Flatten())
model9.add(tf.keras.layers.Dense(units=500, activation=tf.nn.relu))
model9.add(tf.keras.layers.Dense(units=100, activation=tf.nn.relu))
model9.add(tf.keras.layers.Dense(units=50, activation=tf.nn.relu))
model9.add(tf.keras.layers.Dense(units=25, activation=tf.nn.relu))
model9.add(tf.keras.layers.Dense(units=10, activation=tf.nn.sigmoid))
model9.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss='mean_squared_error',metrics=['binary_accuracy'])
model9.fit(standard_train, Y_train, batch_size=1, epochs=2)

Epoch 1/2
2400/2400 [==============================] - 4s 2ms/step - loss: 0.0459 - binary_accuracy: 0.9445
Epoch 2/2
2400/2400 [==============================] - 4s 2ms/step - loss: 0.0252 - binary_accuracy: 0.9710


In [33]:
prediction = model9.predict([standard_test])
prect = []
for i in range(len(prediction)):
    prect.append(np.argmax(prediction[i]))

Consider rewriting this model with the Functional API.


In [34]:
accuracy(labels_test,prect)
confusion(labels_test,prect)

Accuracy:  77.0 %
[[19  0  0  0  0  0  1  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 0  1 18  0  0  0  0  0  1  0]
 [ 0  0  1 13  0  6  0  0  0  0]
 [ 0  0  2  0 12  0  3  0  0  3]
 [ 0  0  2  0  0 18  0  0  0  0]
 [ 0  0  3  0  0  0 17  0  0  0]
 [ 1  0  0  0  2  0  0 15  0  2]
 [ 0  0  0  1  0  5  0  0 14  0]
 [ 1  0  0  2  6  0  0  3  0  8]]


When decreasing the batch size the runtime per epoch increased. Bigger batches mean less total updates in each epoch. Thus when decreasing batches it takes more updates per epoch.